### Your Goal
Predict the probability of various defects on steel plates. Good luck!

In [1]:
# Importing necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from warnings import filterwarnings
filterwarnings('ignore')

In [2]:
# Importing the data
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

# Checking the number of rows and columns of data
print("train: ",train.shape)
print("test: ", test.shape)

train:  (19219, 35)
test:  (12814, 28)


In [3]:
# See the first few lines of train data
train.head()

id  X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  X_Perimeter  \
0   0        584        590     909972     909977            16            8   
1   1        808        816     728350     728372           433           20   
2   2         39        192    2212076    2212144         11388          705   
3   3        781        789    3353146    3353173           210           16   
4   4       1540       1560     618457     618502           521           72   

   Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  ...  \
0            5               2274                    113  ...   
1           54              44478                     70  ...   
2          420            1311391                     29  ...   
3           29               3202                    114  ...   
4           67              48231                     82  ...   

   Orientation_Index  Luminosity_Index  SigmoidOfAreas  Pastry  Z_Scratch  \
0            -0.5000           -0.0104          0.1417       0          0   
1             0.7419           -0.2997          0.9491       0          0   
2            -0.0105           -0.0944          1.0000       0          0   
3             0.6667           -0.0402          0.4025       0          0   
4             0.9158           -0.2455          0.9998       0          0   

   K_Scatch  Stains  Dirtiness  Bumps  Other_Faults  
0         0       1          0      0             0  
1         0       0          0      0             1  
2         1       0          0      0             0  
3         1       0          0      0             0  
4         0       0          0      0             1  

[5 rows x 35 columns]

In [4]:
# See the first few lines of test data
test.head()

id  X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  \
0  19219       1015       1033    3826564    3826588           659   
1  19220       1257       1271     419960     419973           370   
2  19221       1358       1372     117715     117724           289   
3  19222        158        168     232415     232440            80   
4  19223        559        592     544375     544389           140   

   X_Perimeter  Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  ...  \
0           23           46              62357                     67  ...   
1           26           28              39293                     92  ...   
2           36           32              29386                    101  ...   
3           10           11               8586                    107  ...   
4           19           15              15524                    103  ...   

   Outside_X_Index  Edges_X_Index  Edges_Y_Index  Outside_Global_Index  \
0           0.0095         0.5652         1.0000                   1.0   
1           0.0047         0.2414         1.0000                   1.0   
2           0.0155         0.6000         0.7500                   0.0   
3           0.0037         0.8000         1.0000                   1.0   
4           0.0158         0.8421         0.5333                   0.0   

   LogOfAreas  Log_X_Index  Log_Y_Index  Orientation_Index  Luminosity_Index  \
0      2.8410       1.1139       1.6628             0.6727           -0.2261   
1      2.5682       0.9031       1.4472             0.9063           -0.1453   
2      2.4609       1.3222       1.3222            -0.5238           -0.0435   
3      1.9031       0.6990       1.0414             0.1818           -0.0738   
4      2.1461       1.3222       1.1461            -0.5714           -0.0894   

   SigmoidOfAreas  
0          0.9172  
1          0.9104  
2          0.6514  
3          0.2051  
4          0.4170  

[5 rows x 28 columns]

In [5]:
# Checking for missing values
train.isnull().sum()

id                       0
X_Minimum                0
X_Maximum                0
Y_Minimum                0
Y_Maximum                0
Pixels_Areas             0
X_Perimeter              0
Y_Perimeter              0
Sum_of_Luminosity        0
Minimum_of_Luminosity    0
Maximum_of_Luminosity    0
Length_of_Conveyer       0
TypeOfSteel_A300         0
TypeOfSteel_A400         0
Steel_Plate_Thickness    0
Edges_Index              0
Empty_Index              0
Square_Index             0
Outside_X_Index          0
Edges_X_Index            0
Edges_Y_Index            0
Outside_Global_Index     0
LogOfAreas               0
Log_X_Index              0
Log_Y_Index              0
Orientation_Index        0
Luminosity_Index         0
SigmoidOfAreas           0
Pastry                   0
Z_Scratch                0
K_Scatch                 0
Stains                   0
Dirtiness                0
Bumps                    0
Other_Faults             0
dtype: int64

In [6]:
# Checking for missing values
test.isnull().sum()

id                       0
X_Minimum                0
X_Maximum                0
Y_Minimum                0
Y_Maximum                0
Pixels_Areas             0
X_Perimeter              0
Y_Perimeter              0
Sum_of_Luminosity        0
Minimum_of_Luminosity    0
Maximum_of_Luminosity    0
Length_of_Conveyer       0
TypeOfSteel_A300         0
TypeOfSteel_A400         0
Steel_Plate_Thickness    0
Edges_Index              0
Empty_Index              0
Square_Index             0
Outside_X_Index          0
Edges_X_Index            0
Edges_Y_Index            0
Outside_Global_Index     0
LogOfAreas               0
Log_X_Index              0
Log_Y_Index              0
Orientation_Index        0
Luminosity_Index         0
SigmoidOfAreas           0
dtype: int64

In [7]:
# See general information of the train dataset
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19219 entries, 0 to 19218
Data columns (total 35 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     19219 non-null  int64  
 1   X_Minimum              19219 non-null  int64  
 2   X_Maximum              19219 non-null  int64  
 3   Y_Minimum              19219 non-null  int64  
 4   Y_Maximum              19219 non-null  int64  
 5   Pixels_Areas           19219 non-null  int64  
 6   X_Perimeter            19219 non-null  int64  
 7   Y_Perimeter            19219 non-null  int64  
 8   Sum_of_Luminosity      19219 non-null  int64  
 9   Minimum_of_Luminosity  19219 non-null  int64  
 10  Maximum_of_Luminosity  19219 non-null  int64  
 11  Length_of_Conveyer     19219 non-null  int64  
 12  TypeOfSteel_A300       19219 non-null  int64  
 13  TypeOfSteel_A400       19219 non-null  int64  
 14  Steel_Plate_Thickness  19219 non-null  int64  
 15  Ed

In [8]:
# See general information of the test dataset
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12814 entries, 0 to 12813
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   id                     12814 non-null  int64  
 1   X_Minimum              12814 non-null  int64  
 2   X_Maximum              12814 non-null  int64  
 3   Y_Minimum              12814 non-null  int64  
 4   Y_Maximum              12814 non-null  int64  
 5   Pixels_Areas           12814 non-null  int64  
 6   X_Perimeter            12814 non-null  int64  
 7   Y_Perimeter            12814 non-null  int64  
 8   Sum_of_Luminosity      12814 non-null  int64  
 9   Minimum_of_Luminosity  12814 non-null  int64  
 10  Maximum_of_Luminosity  12814 non-null  int64  
 11  Length_of_Conveyer     12814 non-null  int64  
 12  TypeOfSteel_A300       12814 non-null  int64  
 13  TypeOfSteel_A400       12814 non-null  int64  
 14  Steel_Plate_Thickness  12814 non-null  int64  
 15  Ed

In [9]:
# Create input properties by dropping id and 'Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults' columns

X = train.drop(['id','Pastry', 'Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults'], axis=1)
y = train[['Pastry','Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=0)

In [10]:
# Create an XGBoost Classifier using the XGBClassifier class and then fit the training data to the model using the fit() method
from xgboost import XGBClassifier

classifier = XGBClassifier()

classifier.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [11]:
# Make predictions based on input features (X_test) in the test set using a trained regression model
y_pred = classifier.predict(X_test)

In [12]:
print(y_pred)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [13]:
# Create a new data frame by removing certain column from the data frame named "test"
test1 = test.drop(columns = 'id')

In [14]:
# Create a NumPy array by selecting all rows and columns of dataframe test1
unseen = test1.iloc[:, :].values

In [16]:
# Make predictions on "unseen" data with a model called classifier
unseen_pred = classifier.predict(unseen)

In [17]:
import pandas as pd

# Creating DataFrame using 'unseen_pred' array
pred_df = pd.DataFrame(unseen_pred, columns=['Pastry','Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults'])

# Add new columns to your 'test' dataframe
test = pd.concat([test, pred_df], axis=1)

In [18]:
test.head()

id  X_Minimum  X_Maximum  Y_Minimum  Y_Maximum  Pixels_Areas  \
0  19219       1015       1033    3826564    3826588           659   
1  19220       1257       1271     419960     419973           370   
2  19221       1358       1372     117715     117724           289   
3  19222        158        168     232415     232440            80   
4  19223        559        592     544375     544389           140   

   X_Perimeter  Y_Perimeter  Sum_of_Luminosity  Minimum_of_Luminosity  ...  \
0           23           46              62357                     67  ...   
1           26           28              39293                     92  ...   
2           36           32              29386                    101  ...   
3           10           11               8586                    107  ...   
4           19           15              15524                    103  ...   

   Orientation_Index  Luminosity_Index  SigmoidOfAreas  Pastry  Z_Scratch  \
0             0.6727           -0.2261          0.9172     0.0        0.0   
1             0.9063           -0.1453          0.9104     0.0        0.0   
2            -0.5238           -0.0435          0.6514     0.0        0.0   
3             0.1818           -0.0738          0.2051     0.0        0.0   
4            -0.5714           -0.0894          0.4170     0.0        0.0   

   K_Scatch  Stains  Dirtiness  Bumps  Other_Faults  
0       0.0     0.0        0.0    0.0           0.0  
1       0.0     0.0        0.0    0.0           0.0  
2       0.0     0.0        0.0    0.0           0.0  
3       0.0     0.0        0.0    1.0           0.0  
4       0.0     0.0        0.0    0.0           0.0  

[5 rows x 35 columns]

In [19]:
# Train a classifier for each label sequentially and then calculate the AUC score by making predictions on the test set
from sklearn.metrics import roc_auc_score
for i in y:
    classifier.fit(X_train, y_train[i])
    ctbproba = classifier.predict_proba(X_test)[:, 1] 
    print(f'AUC Score - {i}: {roc_auc_score(y_test[i],ctbproba)}\n')
    pred = classifier.predict_proba(X_test)[:, 1]

AUC Score - Pastry: 0.847699214365881

AUC Score - Z_Scratch: 0.9539639511104769

AUC Score - K_Scatch: 0.9873710556179949

AUC Score - Stains: 0.9948941838093829

AUC Score - Dirtiness: 0.9004985961854972

AUC Score - Bumps: 0.8070865292063589

AUC Score - Other_Faults: 0.6667587287961634



In [20]:
#  Create a DataFrame containing predictions
submission = test[['id', 'Pastry','Z_Scratch', 'K_Scatch', 'Stains', 'Dirtiness', 'Bumps', 'Other_Faults']]

#  Convert to the format required by the submission file (for example, CSV format)
submission.to_csv('submission.csv', index=False)